version: '3'

vars:
  PLATFORM: nitroso
  SERVICE: zinc

  CHART_PATH: infra/root_chart
  RELEASE_NAME: nitroso-zinc

includes:
  helm: Taskfile.helm.yml
  tear: tasks/Taskfile.tear.yml
  stop: tasks/Taskfile.stop.yml
  util: tasks/Taskfile.util.yml

tasks:
  setup:
    desc: 'Setup the repository'
    env:
      PLATFORM: '{{.PLATFORM}}'
      SERVICE: '{{.SERVICE}}'
    cmds:
      - ./scripts/local/secrets.sh
      - go mod tidy
  build:
    desc: 'Build the binary'
    cmds:
      - go build -o bin/{{.PLATFORM}}-{{.SERVICE}} .

  run:
    desc: 'Runs the application with secrets'
    cmds:
      - ./scripts/local/run.sh ./config/dev.yaml go run . -- {{.CLI_ARGS}}

  dev:
    desc: 'Dev the application with infrastructure'
    cmds:
      - ./scripts/local/dev.sh ./config/dev.yaml go run . -- {{.CLI_ARGS}}

  dev:watch:
    desc: 'Dev the application with infrastructure in development mode'
    cmds:
      - ./scripts/local/dev.sh ./config/dev.yaml air -- {{.CLI_ARGS}}

  latest:
    desc: Get the latest versions of dependencies
    cmds:
      - task: util:latest-oci
        vars:
          NAME: bromine
          OCI: ghcr.io/atomicloud/sulfoxide.bromine/sulfoxide-bromine
      - task: util:latest-oci
        vars:
          NAME: zinc
          OCI: ghcr.io/atomicloud/nitroso.zinc/root-chart
  process-proxy:
    desc: Process proxy from webshare
    cmds:
      - ./scripts/local/process_proxy.sh {{.CLI_ARGS}}
  update-proxy:
    desc: Update proxy from webshare
    cmds:
      - ./scripts/local/update_proxy.sh
  sdk:gen:
    desc: Generate the SDK
    cmds:
      - ./scripts/local/gen-sdk.sh
