{{- if and .Values.serviceAccount.create .Values.jobRbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "golang-chart.serviceAccountName" . }}
  labels: {{- include "golang-chart.labels" . | nindent 4 }}
  annotations: {{- include "golang-chart.annotations" . | nindent 4 }}
  {{- with .Values.jobRbac.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "golang-chart.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "golang-chart.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}