apiVersion: v2
name: root-chart
description: Root Chart to a single Service

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: golang-chart
    version: 0.1.0
    repository: file://../consumer_chart
    condition: consumer.enabled
    alias: consumer
  - name: sulfoxide-bromine
    version: 1.3.0
    condition: bromine.enable
    alias: bromine
    repository: oci://ghcr.io/atomicloud/sulfoxide.bromine
  - name: root-chart
    version: 1.3.1
    condition: zinc.enable
    alias: zinc
    repository: oci://ghcr.io/atomicloud/nitroso.zinc
