serviceTree: &serviceTree
  landscape: lapras
  platform: nitroso
  service: tin
  layer: "2"

bromine:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  enable: false
  # -- Store name to create
  storeName: nitroso-tin
  # -- Secret of Secrets reference
  rootSecret:
    # -- DOPPLER Token Reference
    ref: "NITROSO_TIN"

  target: &target "nitroso-tin"
cdc:
  enabled: true
  annotations:
    argocd.argoproj.io/sync-wave: "4"

  envFromSecret: *target

  jobRbac:
    create: false

  nameOverride: "tin-cdc"

  serviceTree:
    <<: *serviceTree
    module: cdc

  imagePullSecrets: []

  replicaCount: 1

  appSettings: {}

  configMountPath: /app/config

  image:
    repository: nitroso-tin-cdc
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  resources: {}

  autoscaling: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  topologySpreadConstraints: {}

poller:
  enabled: true
  annotations:
    argocd.argoproj.io/sync-wave: "4"

  envFromSecret: *target

  jobRbac:
    create: true
    annotations:
      argocd.argoproj.io/sync-wave: "4"

  nameOverride: "tin-poller"

  serviceTree:
    <<: *serviceTree
    module: poller

  imagePullSecrets: []

  replicaCount: 1

  appSettings: {}

  configMountPath: /app/config

  image:
    repository: nitroso-tin-poller
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  serviceAccount:
    create: true
    annotations:
      argocd.argoproj.io/sync-wave: "4"

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  resources: {}

  autoscaling: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  topologySpreadConstraints: {}

zinc:
  api:
    configMountPath: /app/Config
    image:
      repository: ghcr.io/atomicloud/nitroso.zinc/api-arm

  migration:
    enabled: false

helium:
  enable: false
  fullnameOverride: "helium-poller"
  bromine:
    target: "nitroso-helium"
    enable: true
    rootSecret:
      name: helium-doppler-secret

livecache:
  nameOverride: tin-livecache
  storage:
    enabled: false

  passwordFromSecret:
    enable: true
    existingSecret:
      key: ATOMI_CACHE__LIVE__PASSWORD
      name: *target
