serviceTree:
  landscape: &landscape pichu

bromine:
  enable: true
  target: &target "nitroso-tin"

# -- YAML Anchor for PodSecurityContext
podSecurityContext: &podSecurityContext
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true

# -- YAML Anchor for SecurityContext
securityContext: &securityContext
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
      - ALL

cdc:
  enabled: true
  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/nitroso.tin/nitroso-tin-amd
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  fullnameOverride: "tin-cdc"
  replicaCount: 1
  configMountPath: /app/config
  command: ["/app/nitroso-tin", "cdc"]

enricher:
  enabled: true
  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/nitroso.tin/nitroso-tin-amd
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  fullnameOverride: "tin-enricher"
  replicaCount: 1
  configMountPath: /app/config
  command: ["/app/nitroso-tin", "enricher"]

poller:
  enabled: true
  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/nitroso.tin/nitroso-tin-amd
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  fullnameOverride: "tin-poller"
  replicaCount: 1
  configMountPath: /app/config
  command: ["/app/nitroso-tin", "poller"]

reserver:
  enabled: true
  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/nitroso.tin/nitroso-tin-amd
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  fullnameOverride: "tin-reserver"
  replicaCount: 1
  configMountPath: /app/config
  command: ["/app/nitroso-tin", "reserver"]

buyer:
  enabled: true
  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/nitroso.tin/nitroso-tin-amd
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  fullnameOverride: "tin-buyer"
  replicaCount: 1
  configMountPath: /app/config
  command: ["/app/nitroso-tin", "buyer"]

zinc:
  enable: false
