serviceTree:
  landscape: &landscape raichu

bromine:
  enable: true
  target: &target "nitroso-tin"

# -- YAML Anchor for PodSecurityContext
podSecurityContext: &podSecurityContext
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true

# -- YAML Anchor for SecurityContext
securityContext: &securityContext
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
      - ALL

cdc:
  enabled: true

  fullnameOverride: "tin-cdc"
  command: ["/app/nitroso-tin", "cdc"]

  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/nitroso.tin/nitroso-tin-amd
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  replicaCount: 2
  configMountPath: /app/config
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

enricher:
  enabled: true

  fullnameOverride: "tin-enricher"
  command: ["/app/nitroso-tin", "enricher"]

  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/nitroso.tin/nitroso-tin-amd
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  replicaCount: 2
  configMountPath: /app/config
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

poller:
  enabled: true

  fullnameOverride: "tin-poller"
  command: ["/app/nitroso-tin", "poller"]

  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/nitroso.tin/nitroso-tin-amd
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  replicaCount: 1
  configMountPath: /app/config

  resources:
    requests:
      memory: "128Mi"
      cpu: "125m"
    limits:
      memory: "256Mi"
      cpu: "250m"

reserver:
  enabled: true

  fullnameOverride: "tin-reserver"
  command: ["/app/nitroso-tin", "reserver"]

  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/nitroso.tin/nitroso-tin-amd
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  replicaCount: 1
  configMountPath: /app/config

  resources:
    requests:
      memory: "3Gi"
      cpu: "3000m"
    limits:
      memory: "4Gi"
      cpu: "4000m"

buyer:
  enabled: true
  fullnameOverride: "tin-buyer"
  command: ["/app/nitroso-tin", "buyer"]

  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/nitroso.tin/nitroso-tin-amd
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext

  replicaCount: 1
  configMountPath: /app/config

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

zinc:
  enable: false

helium:
  enable: false

livecache:
  fullnameOverride: tin-livecache
  commonAnnotations:
    atomi.cloud/landscape: *landscape
  commonLabels:
    atomi.cloud/landscape: *landscape
  podAnnotations:
    atomi.cloud/landscape: *landscape
