serviceTree:
  landscape: &landscape pichu

bromine:
  enable: true
  target: &target "nitroso-tin"

# -- YAML Anchor for PodSecurityContext
podSecurityContext: &podSecurityContext
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true

# -- YAML Anchor for SecurityContext
securityContext: &securityContext
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
      - ALL

cdc:
  enabled: true

  fullnameOverride: "tin-cdc"
  command: ["/app/nitroso-tin", "cdc"]

  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/nitroso.tin/nitroso-tin
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  replicaCount: 1
  configMountPath: /app/config
  resources:
    requests:
      memory: "25Mi"
      cpu: "5m"
    limits:
      memory: "256Mi"
      cpu: "250m"

enricher:
  enabled: true

  fullnameOverride: "tin-enricher"
  command: ["/app/nitroso-tin", "enricher"]

  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/nitroso.tin/nitroso-tin
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  replicaCount: 1
  configMountPath: /app/config
  resources:
    requests:
      memory: "25Mi"
      cpu: "5m"
    limits:
      memory: "256Mi"
      cpu: "250m"

poller:
  enabled: true

  fullnameOverride: "tin-poller"
  command: ["/app/nitroso-tin", "poller"]

  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/nitroso.tin/nitroso-tin
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  replicaCount: 3
  configMountPath: /app/config

  resources:
    requests:
      memory: "25Mi"
      cpu: "5m"
    limits:
      memory: "256Mi"
      cpu: "250m"

reserver:
  enabled: true

  fullnameOverride: "tin-reserver"
  command: ["/app/nitroso-tin", "reserver"]

  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/nitroso.tin/nitroso-tin
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  replicaCount: 1
  configMountPath: /app/config
  resources:
    requests:
      memory: "128Mi"
      cpu: "125m"
    limits:
      memory: "256Mi"
      cpu: "250m"

buyer:
  enabled: true
  fullnameOverride: "tin-buyer"
  command: ["/app/nitroso-tin", "buyer"]

  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/nitroso.tin/nitroso-tin
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext

  replicaCount: 1
  configMountPath: /app/config

  resources:
    requests:
      memory: "25Mi"
      cpu: "25m"
    limits:
      memory: "256Mi"
      cpu: "250m"

zinc:
  enable: false

helium:
  enable: false

livecache:
  fullnameOverride: tin-livecache
  commonAnnotations:
    atomi.cloud/landscape: *landscape
  commonLabels:
    atomi.cloud/landscape: *landscape
  podAnnotations:
    atomi.cloud/landscape: *landscape
