serviceTree:
  landscape: &landscape lapras

consumer:
  enabled: true
  serviceTree:
    landscape: *landscape

  imagePullSecrets: []

  replicaCount: 1

  configMountPath: /app/config

zinc:
  enable: true
  serviceTree:
    landscape: *landscape
  api:
    enabled: true
    replicaCount: 1
    configMountPath: /app/Config
    appSettings:
      Database:
        MAIN:
          AutoMigrate: true
    service:
      type: ClusterIP
      port: 80
      containerPort: 9001
    serviceTree:
      landscape: *landscape
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: api.zinc.nitroso.lapras.lvh.me
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []

  migration:
    enabled: false
  maincache:
    enable: true
  maindb:
    enable: true
  mainstorage:
    enable: true
