serviceTree:
  landscape: &landscape pichu

bromine:
  enable: true
  target: &target "nitroso-tin"

# -- YAML Anchor for PodSecurityContext
podSecurityContext: &podSecurityContext
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true

# -- YAML Anchor for SecurityContext
securityContext: &securityContext
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
      - ALL

consumer:
  enabled: true
  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/nitroso.tin/consumer-amd
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext

  replicaCount: 1

  configMountPath: /app/config

zinc:
  enable: false
