cache:
  MAIN:
    ssl: true
  LIVE:
    password: ""
  STREAM:
    password: ""
app:
  landscape: pichu

auth:
  descope:
    descopeId: P2Ya3WPmBmUBwJzhWoVB5uNeK7gg
    descopeAccessKey: ""

enricher:
  email: xxluna001@gmail.com

buyer:
  scheme: http
  host: zinc-api
  port: 80

cdc:
  group: cdc
  scheme: http
  host: zinc-api
  port: 80
  parallelism: 8

poller:
  backoffLimit: 3
  pollee:
    namespace: "nitroso"
    image: "ghcr.io/atomicloud/nitroso.helium/nitroso-helium"
    version: "1.9.2"
    secretRef: "nitroso-helium"
    configRef: "helium-pollee-config"

otel:
  log:
    zerolog:
      timeFormat: rfc3339
      stacktrace: true
      pretty: false
      caller: true
  metric:
    enable: false
    reader: {}
    exporter:
      exporterType: console
      console:
        prettyPrint: true
        timestamp: true
  trace:
    enable: true
    processor:
      processorType: batch
      batchProcessorConfig: {}
    exporter:
      exporterType: otlp
      otlp:
        protocol: http
        endpoint: silicon-otlp-collector.sulfoxide.svc:4318
        insecure: true
        compression: gzip
