cache:
  MAIN:
    password: ""
    ssl: false
    endpoints:
      0: localhost:6379
app:
  landscape: lapras

otel:
  metric:
    enable: false
    reader: {}
    exporter:
      exporterType: console
      console:
        prettyPrint: true
        timestamp: true
  trace:
    enable: true
    processor:
      processorType: batch
      batchProcessorConfig: {}
    exporter:
      exporterType: otlp
      otlp:
        protocol: http
        endpoint: localhost:4318
        insecure: true
        compression: gzip
