cache:
  MAIN:
    password: 'supersecret'
    ssl: false
    endpoints:
      0: zinc-maincache:6379
  STREAM:
    password: ''
    ssl: false
    endpoints:
      0: zinc-streamcache-master:6379
  LIVE:
    password: ''
    ssl: false
    endpoints:
      0: tin-livecache-master:6379
app:
  landscape: lapras

auth:
  descope:
    descopeId: P2Ya46UVwFV8nTwNGZWpxRtyL7Jj
    descopeAccessKey: ''

enricher:
  email: kirinnee97@gmail.com

buyer:
  scheme: http
  host: zinc-api
  port: 80

cdc:
  group: cdc
  scheme: http
  host: zinc-api
  port: 80
  parallelism: 8

poller:
  backoffLimit: 3
  pollee:
    namespace: 'nitroso'
    image: 'ghcr.io/atomicloud/nitroso.helium/nitroso-helium'
    version: '1.6.0'
    secretRef: 'nitroso-helium'
    configRef: 'helium-poller-config'

otel:
  log:
    zerolog:
      stacktrace: true
      pretty: true
      caller: true
  metric:
    enable: true
    reader: {}
    exporter:
      exporterType: console
      console:
        prettyPrint: true
        timestamp: true
  trace:
    enable: true
    processor:
      processorType: batch
      batchProcessorConfig: {}
    exporter:
      exporterType: console
      otlp:
        protocol: http
        endpoint: localhost:4318
        insecure: true
        compression: gzip
