serviceTree:
  landscape: lapras
  platform: nitroso
  service: tin
  module: consumer

stateful: false

replicaCount: 1
appSettings: {}

configMountPath: /app/config

image:
  repository: golang-chart
  pullPolicy: IfNotPresent
  tag: ""

env:
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

jobRbac:
  create: false
  annotations: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

autoscaling: {}

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints: {}
